### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by noirscape** [ev1l0rd/dwarffortresnsis#3]
- [x] Include Dwarf Fortress (0.42.06)
- [x] Include Dwarf Therapist
-  Include dfhack (On indefinite hold)
- [x] Include soundsense
-  Include stonesense (On indefinite hold)
- [x] Include code for texture packs.
- [x] Include option for audio.
- [x] Include various settings
- [x] Display License
# Notes
- DFHack and stonesense are on hold due to a lack of a stable version for 0.42.06.

**Comment by noirscape** [comment]
With release 0.2-alpha, the following goals have been met:
- Display License

**Comment by noirscape** [comment]
With release 0.3-alpha, the following goals have been met:
- Include option for audio

**Comment by noirscape** [comment]
With release 0.4-alpha, the following goals have been met:
- Include soundsense.
- Include various settings.

**Comment by noirscape** [comment]
Wrote the wikipage for graphics code. 1.0 is here!
